### ISSUE TITLE
Allow customizing default chat map

### ISSUE THREAD

**Issue by dennwc** [opennox/opennox#606]
Tracked to `nox_client_getChatMap_49FF40` which sets chat map depending on where you put the server pin/flag on the Nox world map. We should override that instead.

**Comment by dennwc** [comment]
The new version will allow changing it in the config:
```yml
server:
  maps:
    default_chat: so_lod
```
